project:
  type: website

website:
  title: "Bella Gordon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Minty
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto